### ISSUE TITLE
Line 61 of current VoxelParse.py

### ISSUE THREAD

**Issue by max3925vats** [garde-group/ProteinPatchAnalysis#2]
Line 61: `for residue in structure[0][' '].get_list():`
gives the following error:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-10-0a1838a47a9b> in <module>()
     31         oxygen_density = np.zeros([np.shape(linx)[0],np.shape(liny)[0],np.shape(linz)[0]])
     32         sulfur_density = np.zeros([np.shape(linx)[0],np.shape(liny)[0],np.shape(linz)[0]])
---> 33         for residue in structure[0][' '].get_list():
     34             # print('Assessing Residue', residue)
     35             for atom in residue.get_list():

~/anaconda3/envs/idp/lib/python3.6/site-packages/Bio/PDB/Entity.py in __getitem__(self, id)
     39     def __getitem__(self, id):
     40         """Return the child with given id."""
---> 41         return self.child_dict[id]
     42 
     43     def __delitem__(self, id):

KeyError: ' '

```
I have the following Biopython:
```
# Name                    Version                   Build  Channel
biopython                 1.73             py36h7b6447c_0    anaconda

```
This works for me:
`for residue in structure.get_residues():`

Same for other instances of this use as well.

**Comment by cbilodeau2** [comment]
There might be a difference in the way the biopython loads ubiquitin as opposed to the fab pdb (which is a fully stripped down file in that it contains only the necessary coordinate lines). Try doing this with the fab A pdb and see if it works. Additionally, check if the structure of ubiquitin has chains. I think this relates to the fact that we need a pdb cleaning pipeline.

**Comment by max3925vats** [comment]
Issue persists with fabA.pdb too. For now, I have modified the voxel py script in my branch to get_residues().

**Comment by cbilodeau2** [comment]
I have converted your generator to a list: list(structure.get_residues()), this way its a little easier to manipulate. Let me know if this causes you problems.
