### ISSUE TITLE
PDB Cleaning Pipeline

### ISSUE THREAD

**Issue by cbilodeau2** [garde-group/ProteinPatchAnalysis#3]
Write shell script (or series of scripts) that takes a list of pdbs and uses amber tools to clean them (meaning delete any heteroatoms, remove any lines that make them incompatible with other scripts). Because this requires amber tools, it will only be able to be run on the linux workstations and we should also be cognizant of the fact that it might work differently if people are running different versions of amber. Ultimately, the workflow should have dirty pdbs (pdbs unmodified from their PDB database entry) in one folder and clean pdbs in the another.

**Comment by max3925vats** [comment]
Added a simple shell script (in my branch) to remove water and heteroatoms, and reduce to fulfil hydrogens. Loops through all pdbs in raw_pdb and saves cleaned pdbs into pdb folder
